---
- hosts: databases
  roles:
    - mariadb
  become: yes

- hosts: balancers
  roles:
    - haproxy
  become: yes
  vars:
    servers: "{{ groups['balancers'] }}"

- host: webservers
  roles:
    - apache
    - php
    - wordpress
  become: yes