---
- hosts: databases
  roles:
    - mariadb
    - wordpress-mariadb
  become: yes

- hosts: balancers
  roles:
    - haproxy
  become: yes
  vars:
    servers: "{{ groups['balancers'] }}"

- include: webservers.yml